### ISSUE TITLE
macOS jbr11 `java` executable not found by AgentLoader

### ISSUE THREAD

**Issue by ArtsiomCh** [avaje-common/avaje-agentloader#9]
Using avaje-agentloader under macOS Catalina with built-in  JetBrains Runtime (jbr11?) at Clion 2019.2.1 (192.6262.62) cause next execption:
```
java.lang.RuntimeException: java.io.IOException: Cannot run program ""/Users/csita/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/192.6262.62/CLion.app/Contents/jbr/Contents/Home/bin/java"": error=2, No such file or directory
at org.avaje.agentloader.AgentLoader.loadAgent(AgentLoader.java:92)
at org.avaje.agentloader.AgentLoader.loadAgent(AgentLoader.java:70)
```
**See more details here: https://github.com/ArtsiomCh/CMake/issues/5**

Looks for me like org.avaje.agentloader.load.ExternalLoader#loadAgent can't make proper `cmd` value: `.../192.6262.62/CLion.app/Contents/jbr/Contents/Home/bin/java` doesn't look to be correct path to `java`.

Unfortunately, I have no macOS to check it...

**Comment by ArtsiomCh** [comment]
The actual problem happens causes `java.lang.ProcessBuilder` seems to already do quotation if any param contains whitespace. So doing quotation before calling ProcessBuilder, make params ""doubly double-quoted"" and of course params become invalid.
